-- Fresh PostgreSQL installations only: complete application schema at V25.
-- Flyway B25 is ignored by databases with an existing migration history.
-- No customer, organization, membership, permission, or attachment data is seeded.
--
-- PostgreSQL database dump
--


-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11


--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';




--
-- Name: agent_presence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_presence (
    id character varying(64) NOT NULL,
    issuer character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    organization_id character varying(64) NOT NULL,
    display_name character varying(100) NOT NULL,
    availability character varying(32) NOT NULL,
    heartbeat_at timestamp with time zone,
    available_since timestamp with time zone NOT NULL,
    work_queue_code character varying(64),
    state_revision bigint DEFAULT 0 NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: assignment_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assignment_attempts (
    id character varying(64) NOT NULL,
    organization_id character varying(64) NOT NULL,
    queue_code character varying(64) NOT NULL,
    presence_id character varying(64) NOT NULL,
    agent_issuer character varying(255) NOT NULL,
    agent_subject character varying(255) NOT NULL,
    agent_name character varying(100) NOT NULL,
    routing_cycle integer NOT NULL,
    offered_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    received_at timestamp with time zone,
    finished_at timestamp with time zone,
    outcome character varying(32) NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attachments (
    id bigint NOT NULL,
    organization_id character varying(64),
    file_id character varying(255) NOT NULL,
    kind character varying(255),
    name character varying(255),
    queue_code character varying(255) NOT NULL,
    request_id character varying(255) NOT NULL,
    sha256 character varying(255),
    size bigint NOT NULL,
    owner_issuer character varying(255),
    owner_subject character varying(255),
    team_id character varying(64)
);


--
-- Name: attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_events (
    id bigint NOT NULL,
    organization_id character varying(255),
    actor_issuer character varying(255) NOT NULL,
    actor_subject character varying(255) NOT NULL,
    action character varying(255) NOT NULL,
    target character varying(255),
    details character varying(6000),
    occurred_at timestamp with time zone NOT NULL
);


--
-- Name: audit_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: call_recordings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.call_recordings (
    id character varying(64) NOT NULL,
    organization_id character varying(64) NOT NULL,
    owner_issuer character varying(255),
    owner_subject character varying(255),
    team_id character varying(64),
    queue_code character varying(64) NOT NULL,
    state character varying(32) NOT NULL,
    egress_id character varying(128),
    file_id character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    retry_at timestamp with time zone NOT NULL,
    lease_until timestamp with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    error_code character varying(64),
    duration_seconds bigint DEFAULT 0 NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    queue_id bigint NOT NULL,
    sequence bigint NOT NULL,
    sender_key character varying(600) NOT NULL,
    sender character varying(16) NOT NULL,
    sender_name text NOT NULL,
    client_message_id character varying(36) NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    image_file_id character varying(255),
    image_name character varying(255),
    image_mime character varying(32),
    image_size bigint,
    image_sha256 character varying(64),
    CONSTRAINT chat_message_content CHECK (((length(body) >= 0) AND (length(body) <= 10000) AND ((length(body) > 0) OR (image_file_id IS NOT NULL)))),
    CONSTRAINT chat_message_image CHECK ((((image_file_id IS NULL) AND (image_name IS NULL) AND (image_mime IS NULL) AND (image_size IS NULL) AND (image_sha256 IS NULL)) OR (((sender)::text = 'CUSTOMER'::text) AND (image_file_id IS NOT NULL) AND (image_name IS NOT NULL) AND (image_mime IS NOT NULL) AND ((image_mime)::text = ANY (ARRAY[('image/jpeg'::character varying)::text, ('image/png'::character varying)::text])) AND (image_size IS NOT NULL) AND ((image_size >= 1) AND (image_size <= 52428800)) AND (image_sha256 IS NOT NULL)))),
    CONSTRAINT chat_messages_sender_check CHECK (((sender)::text = ANY (ARRAY[('CUSTOMER'::character varying)::text, ('AGENT'::character varying)::text]))),
    CONSTRAINT chat_messages_sequence_check CHECK ((sequence > 0))
);


--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chat_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chat_messages_id_seq OWNED BY public.chat_messages.id;


--
-- Name: consultation_catalogs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consultation_catalogs (
    owner_id character varying(64) NOT NULL,
    overridden boolean NOT NULL,
    document text NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: consultation_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consultation_revisions (
    id bigint NOT NULL,
    organization_id character varying(64) NOT NULL,
    consultation_id bigint NOT NULL,
    actor_subject character varying(255),
    actor_name character varying(255),
    changed_at timestamp with time zone,
    before_document text,
    owner_issuer character varying(255),
    owner_subject character varying(255),
    team_id character varying(64)
);


--
-- Name: consultation_revisions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.consultation_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: consultation_revisions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.consultation_revisions_id_seq OWNED BY public.consultation_revisions.id;


--
-- Name: consultations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consultations (
    id bigint NOT NULL,
    agent_name character varying(100),
    call_duration_seconds integer NOT NULL,
    category_main character varying(100) NOT NULL,
    category_sub character varying(100) NOT NULL,
    created_at timestamp(6) without time zone,
    customer_code character varying(64),
    memo text,
    status character varying(32) NOT NULL,
    tags character varying(255),
    version bigint DEFAULT 0,
    organization_id character varying(64),
    agent_subject character varying(255),
    editor_document text,
    queue_code character varying(64),
    request_key character varying(64),
    owner_issuer character varying(255),
    owner_subject character varying(255),
    team_id character varying(64),
    category_id character varying(64),
    category_path text,
    result_id character varying(64),
    result_name character varying(100),
    current_assignee_name character varying(255),
    CONSTRAINT consultations_status_check CHECK (((status)::text = ANY (ARRAY[('IN_PROGRESS'::character varying)::text, ('COMPLETED'::character varying)::text, ('ESCALATED'::character varying)::text])))
);


--
-- Name: consultations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.consultations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consultations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_history_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_history_links (
    id character varying(64) NOT NULL,
    organization_id character varying(64) NOT NULL,
    queue_code character varying(64) NOT NULL,
    customer_code character varying(64) NOT NULL,
    original_registered boolean NOT NULL,
    actor_issuer character varying(255) NOT NULL,
    actor_subject character varying(255) NOT NULL,
    actor_name character varying(100) NOT NULL,
    linked_at timestamp with time zone NOT NULL,
    undone_at timestamp with time zone
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    code character varying(64) NOT NULL,
    company character varying(150),
    complainant boolean NOT NULL,
    created_at timestamp(6) without time zone,
    customer_notes text,
    customer_type character varying(32) NOT NULL,
    department character varying(100),
    email character varying(150),
    last_contact_at timestamp(6) without time zone,
    manager_name character varying(100),
    name character varying(100),
    phone_number character varying(50) NOT NULL,
    registered boolean NOT NULL,
    tier character varying(32),
    title character varying(100),
    total_calls integer NOT NULL,
    updated_at timestamp(6) without time zone,
    organization_id character varying(64),
    owner_issuer character varying(255),
    owner_subject character varying(255),
    team_id character varying(64),
    CONSTRAINT customers_customer_type_check CHECK (((customer_type)::text = ANY (ARRAY[('CORPORATE'::character varying)::text, ('INDIVIDUAL'::character varying)::text])))
);


--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: follow_up_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.follow_up_actions (
    id bigint NOT NULL,
    action_type character varying(50) NOT NULL,
    created_at timestamp(6) without time zone,
    customer_code character varying(64),
    details text,
    status character varying(32) NOT NULL,
    title character varying(200) NOT NULL,
    organization_id character varying(64),
    queue_code character varying(64),
    owner_issuer character varying(255),
    owner_subject character varying(255),
    team_id character varying(64),
    version bigint DEFAULT 0 NOT NULL,
    proposed_at timestamp with time zone,
    scheduled_at timestamp with time zone,
    scheduled_end_at timestamp with time zone,
    time_zone character varying(100),
    duration_minutes integer,
    assigned_member_id bigint,
    assigned_name character varying(255),
    creator_issuer character varying(255),
    creator_subject character varying(255),
    creator_name character varying(255),
    updated_at timestamp with time zone,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    outcome text,
    request_key character varying(64),
    request_fingerprint character varying(64),
    CONSTRAINT follow_up_confirmed_interval CHECK (((((status)::text <> ALL (ARRAY[('ASSIGNED'::character varying)::text, ('SCHEDULED'::character varying)::text, ('IN_PROGRESS'::character varying)::text])) OR ((assigned_member_id IS NOT NULL) AND (owner_issuer IS NOT NULL) AND (owner_subject IS NOT NULL))) AND (((status)::text <> ALL (ARRAY[('SCHEDULED'::character varying)::text, ('IN_PROGRESS'::character varying)::text])) OR (((status)::text = 'IN_PROGRESS'::text) AND ((action_type)::text = 'CALLBACK'::text) AND (scheduled_at IS NULL) AND (scheduled_end_at IS NULL)) OR ((scheduled_at IS NOT NULL) AND (scheduled_end_at IS NOT NULL) AND (scheduled_end_at > scheduled_at) AND (duration_minutes IS NOT NULL) AND ((duration_minutes >= 5) AND (duration_minutes <= 480)) AND (time_zone IS NOT NULL))) AND (((status)::text <> 'ASSIGNED'::text) OR ((action_type)::text = 'CALLBACK'::text))))
);


--
-- Name: follow_up_actions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.follow_up_actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follow_up_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: follow_up_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.follow_up_events (
    id bigint NOT NULL,
    organization_id character varying(64) NOT NULL,
    follow_up_id bigint NOT NULL,
    action character varying(32) NOT NULL,
    actor_issuer character varying(255) NOT NULL,
    actor_subject character varying(255) NOT NULL,
    actor_name character varying(255) NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    reason character varying(2000) NOT NULL,
    before_snapshot text,
    after_snapshot text NOT NULL
);


--
-- Name: follow_up_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.follow_up_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follow_up_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: internal_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.internal_messages (
    id bigint NOT NULL,
    room_id character varying(64) NOT NULL,
    sequence bigint NOT NULL,
    sender_issuer character varying(255) NOT NULL,
    sender_subject character varying(255) NOT NULL,
    sender_name character varying(255) NOT NULL,
    client_message_id character varying(36) NOT NULL,
    body text NOT NULL,
    attachment_ids text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT internal_messages_body_check CHECK ((length(body) <= 10000)),
    CONSTRAINT internal_messages_sequence_check CHECK ((sequence > 0))
);


--
-- Name: internal_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.internal_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: internal_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.internal_messages_id_seq OWNED BY public.internal_messages.id;


--
-- Name: internal_room_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.internal_room_members (
    id character varying(255) NOT NULL,
    room_id character varying(64) NOT NULL,
    membership_id bigint NOT NULL,
    active boolean NOT NULL,
    read_sequence bigint NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    left_at timestamp with time zone,
    CONSTRAINT internal_room_members_read_sequence_check CHECK ((read_sequence >= 0))
);


--
-- Name: internal_rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.internal_rooms (
    id character varying(255) NOT NULL,
    version bigint NOT NULL,
    organization_id character varying(64) NOT NULL,
    owner_issuer character varying(255) NOT NULL,
    owner_subject character varying(255) NOT NULL,
    team_id character varying(64),
    kind character varying(16) NOT NULL,
    name character varying(150) NOT NULL,
    creation_key character varying(64) NOT NULL,
    creator_member_id bigint NOT NULL,
    sequence bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT internal_rooms_kind_check CHECK (((kind)::text = ANY (ARRAY[('DIRECT'::character varying)::text, ('GROUP'::character varying)::text]))),
    CONSTRAINT internal_rooms_sequence_check CHECK ((sequence >= 0))
);


--
-- Name: invitation_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invitation_permissions (
    invitation_id character varying(255) NOT NULL,
    permission character varying(255)
);


--
-- Name: knowledge_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_documents (
    id character varying(255) NOT NULL,
    version bigint NOT NULL,
    organization_id character varying(64) NOT NULL,
    owner_issuer character varying(255) NOT NULL,
    owner_subject character varying(255) NOT NULL,
    team_id character varying(64),
    title character varying(200) NOT NULL,
    category character varying(100) NOT NULL,
    kind character varying(16) NOT NULL,
    visibility character varying(16) NOT NULL,
    state character varying(16) NOT NULL,
    document text NOT NULL,
    body_text text NOT NULL,
    attachment_ids text NOT NULL,
    draft_revision bigint NOT NULL,
    published_revision bigint,
    published_title character varying(200),
    published_category character varying(100),
    published_body_text text,
    published_kind character varying(16),
    published_visibility character varying(16),
    author_name character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT knowledge_documents_check CHECK ((((state)::text <> 'PUBLISHED'::text) OR (published_revision IS NOT NULL))),
    CONSTRAINT knowledge_documents_draft_revision_check CHECK ((draft_revision > 0)),
    CONSTRAINT knowledge_documents_kind_check CHECK (((kind)::text = ANY (ARRAY[('DOCUMENT'::character varying)::text, ('FAQ'::character varying)::text]))),
    CONSTRAINT knowledge_documents_state_check CHECK (((state)::text = ANY (ARRAY[('DRAFT'::character varying)::text, ('PUBLISHED'::character varying)::text, ('ARCHIVED'::character varying)::text]))),
    CONSTRAINT knowledge_documents_visibility_check CHECK (((visibility)::text = ANY (ARRAY[('SELF'::character varying)::text, ('TEAM'::character varying)::text, ('ORGANIZATION'::character varying)::text])))
);


--
-- Name: knowledge_revisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_revisions (
    id bigint NOT NULL,
    document_id character varying(64) NOT NULL,
    revision bigint NOT NULL,
    title character varying(200) NOT NULL,
    category character varying(100) NOT NULL,
    kind character varying(16) NOT NULL,
    visibility character varying(16) NOT NULL,
    document text NOT NULL,
    attachment_ids text NOT NULL,
    editor_issuer character varying(255) NOT NULL,
    editor_subject character varying(255) NOT NULL,
    editor_name character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT knowledge_revisions_revision_check CHECK ((revision > 0))
);


--
-- Name: knowledge_revisions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.knowledge_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: knowledge_revisions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.knowledge_revisions_id_seq OWNED BY public.knowledge_revisions.id;


--
-- Name: membership_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership_permissions (
    membership_id bigint NOT NULL,
    permissions character varying(255)
);


--
-- Name: membership_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership_roles (
    membership_id bigint NOT NULL,
    role_id character varying(64) NOT NULL
);


--
-- Name: memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memberships (
    id bigint NOT NULL,
    active boolean NOT NULL,
    data_scope character varying(255) NOT NULL,
    issuer character varying(255) NOT NULL,
    organization_id character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    display_name character varying(100),
    team_id character varying(64),
    login_id character varying(255),
    identity_name character varying(255),
    deleted boolean DEFAULT false NOT NULL
);


--
-- Name: memberships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organization_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_invitations (
    id character varying(255) NOT NULL,
    organization_id character varying(255) NOT NULL,
    issuer character varying(255) NOT NULL,
    recipient_email character varying(255) NOT NULL,
    token_hash character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    cancelled boolean DEFAULT false NOT NULL,
    accepted_subject character varying(255)
);


--
-- Name: organization_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_roles (
    id character varying(255) NOT NULL,
    organization_id character varying(64) NOT NULL,
    name character varying(100) NOT NULL,
    active boolean NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organizations (
    id character varying(64) NOT NULL,
    active boolean NOT NULL,
    name character varying(255) NOT NULL,
    public_code character varying(255)
);


--
-- Name: queue_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.queue_items (
    id bigint NOT NULL,
    code character varying(64) NOT NULL,
    company_name character varying(150),
    complainant boolean NOT NULL,
    created_at timestamp(6) without time zone,
    customer_name character varying(100) NOT NULL,
    customer_type character varying(32) NOT NULL,
    phone_number character varying(50) NOT NULL,
    priority character varying(32),
    registered boolean NOT NULL,
    status character varying(32) NOT NULL,
    summary text,
    type character varying(32) NOT NULL,
    unread boolean NOT NULL,
    wait_time_or_schedule character varying(50),
    assigned_agent character varying(100),
    inquiry_type character varying(100),
    session_id character varying(100),
    call_ended boolean DEFAULT false NOT NULL,
    version bigint DEFAULT 0,
    organization_id character varying(64),
    assigned_subject character varying(255),
    customer_code character varying(64),
    media_cleanup_until timestamp(6) with time zone,
    request_key character varying(255),
    owner_issuer character varying(255),
    owner_subject character varying(255),
    team_id character varying(64),
    phone_key character varying(50),
    routing_cycle integer DEFAULT 0 NOT NULL,
    support_expires_at timestamp with time zone,
    request_fingerprint character varying(64),
    media_agent_identity character varying(255),
    media_requested_at timestamp with time zone,
    call_started_at timestamp with time zone,
    call_ended_at timestamp with time zone,
    media_missing_since timestamp with time zone,
    callback_due_at timestamp with time zone,
    callback_follow_up_id bigint,
    first_accepted_at timestamp with time zone,
    chat_enabled boolean DEFAULT false NOT NULL,
    chat_sequence bigint DEFAULT 0 NOT NULL,
    chat_ended_at timestamp with time zone,
    CONSTRAINT queue_items_customer_type_check CHECK (((customer_type)::text = ANY (ARRAY[('CORPORATE'::character varying)::text, ('INDIVIDUAL'::character varying)::text]))),
    CONSTRAINT queue_items_status_check CHECK (((status)::text = ANY (ARRAY[('WAITING'::character varying)::text, ('PROCESSING'::character varying)::text, ('COMPLETED'::character varying)::text, ('CANCELLED'::character varying)::text]))),
    CONSTRAINT queue_items_type_check CHECK (((type)::text = ANY (ARRAY[('CALL'::character varying)::text, ('CALLBACK'::character varying)::text, ('TICKET'::character varying)::text])))
);


--
-- Name: queue_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.queue_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.queue_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_grants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_grants (
    role_id character varying(255) NOT NULL,
    permission character varying(100) NOT NULL,
    data_scope character varying(32) NOT NULL,
    CONSTRAINT role_grants_data_scope_check CHECK (((data_scope)::text = ANY (ARRAY[('SELF'::character varying)::text, ('TEAM'::character varying)::text, ('ORGANIZATION'::character varying)::text])))
);


--
-- Name: routing_lock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.routing_lock (
    id integer NOT NULL
);


--
-- Name: support_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.support_settings (
    owner_id character varying(255) NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    title character varying(150),
    description character varying(500),
    button_label character varying(100),
    primary_color character varying(7),
    logo_url character varying(1000)
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teams (
    id character varying(255) NOT NULL,
    organization_id character varying(64) NOT NULL,
    name character varying(100) NOT NULL,
    parent_id character varying(64),
    active boolean NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


--
-- Name: text_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.text_templates (
    id character varying(64) NOT NULL,
    scope character varying(32) NOT NULL,
    organization_id character varying(64) NOT NULL,
    origin_id character varying(64),
    owner_issuer character varying(255),
    owner_subject character varying(255),
    name character varying(150) NOT NULL,
    body text NOT NULL,
    active boolean NOT NULL,
    inherited boolean NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT text_templates_check CHECK (((((scope)::text = 'PERSONAL'::text) AND (owner_issuer IS NOT NULL) AND (owner_subject IS NOT NULL) AND (origin_id IS NULL)) OR (((scope)::text <> 'PERSONAL'::text) AND (owner_issuer IS NULL) AND (owner_subject IS NULL)))),
    CONSTRAINT text_templates_check1 CHECK ((((scope)::text = 'ORGANIZATION'::text) OR (origin_id IS NULL))),
    CONSTRAINT text_templates_scope_check CHECK (((scope)::text = ANY (ARRAY[('COMMON'::character varying)::text, ('ORGANIZATION'::character varying)::text, ('PERSONAL'::character varying)::text])))
);


--
-- Name: timeline_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.timeline_items (
    id bigint NOT NULL,
    agent_name character varying(100) NOT NULL,
    audio_duration character varying(32),
    channel character varying(32) NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_code character varying(64),
    has_audio boolean NOT NULL,
    tags character varying(255),
    title character varying(200) NOT NULL,
    organization_id character varying(64),
    queue_code character varying(64),
    owner_issuer character varying(255),
    owner_subject character varying(255),
    team_id character varying(64),
    CONSTRAINT timeline_items_channel_check CHECK (((channel)::text = ANY (ARRAY[('CALL'::character varying)::text, ('EMAIL'::character varying)::text, ('CHAT'::character varying)::text, ('TICKET'::character varying)::text])))
);


--
-- Name: timeline_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.timeline_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeline_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_files (
    id character varying(255) NOT NULL,
    organization_id character varying(64) NOT NULL,
    owner_kind character varying(16) NOT NULL,
    owner_id character varying(64) NOT NULL,
    uploader_issuer character varying(255) NOT NULL,
    uploader_subject character varying(255) NOT NULL,
    request_id character varying(36) NOT NULL,
    platform_file_id character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    mime character varying(120) NOT NULL,
    size bigint NOT NULL,
    sha256 character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    message_sequence bigint,
    CONSTRAINT work_files_check CHECK ((((owner_kind)::text = 'ROOM'::text) OR (message_sequence IS NULL))),
    CONSTRAINT work_files_message_sequence_check CHECK ((message_sequence > 0)),
    CONSTRAINT work_files_owner_kind_check CHECK (((owner_kind)::text = ANY (ARRAY[('KNOWLEDGE'::character varying)::text, ('ROOM'::character varying)::text]))),
    CONSTRAINT work_files_size_check CHECK (((size >= 1) AND (size <= 52428800)))
);


--
-- Name: work_transfer_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_transfer_events (
    id bigint NOT NULL,
    organization_id character varying(64) NOT NULL,
    transfer_id character varying(36) NOT NULL,
    action character varying(32) NOT NULL,
    actor_issuer character varying(255) NOT NULL,
    actor_subject character varying(255) NOT NULL,
    actor_name character varying(255) NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    reason character varying(2000) NOT NULL
);


--
-- Name: work_transfer_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.work_transfer_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_transfer_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_transfers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_transfers (
    id character varying(36) NOT NULL,
    organization_id character varying(64) NOT NULL,
    consultation_id bigint NOT NULL,
    queue_code character varying(64),
    version bigint DEFAULT 0 NOT NULL,
    record_version bigint NOT NULL,
    from_member_id bigint NOT NULL,
    from_issuer character varying(255) NOT NULL,
    from_subject character varying(255) NOT NULL,
    from_name character varying(255) NOT NULL,
    to_member_id bigint NOT NULL,
    to_issuer character varying(255) NOT NULL,
    to_subject character varying(255) NOT NULL,
    to_name character varying(255) NOT NULL,
    to_team_id character varying(64),
    requester_issuer character varying(255) NOT NULL,
    requester_subject character varying(255) NOT NULL,
    requester_name character varying(255) NOT NULL,
    owner_issuer character varying(255),
    owner_subject character varying(255),
    team_id character varying(64),
    status character varying(32) NOT NULL,
    reason character varying(2000) NOT NULL,
    memo text NOT NULL,
    requested_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    finished_at timestamp with time zone,
    outcome character varying(2000),
    request_key character varying(64) NOT NULL,
    request_fingerprint character varying(64) NOT NULL,
    live_work boolean DEFAULT false NOT NULL,
    kind character varying(16) DEFAULT 'WORK'::character varying NOT NULL,
    from_media_identity character varying(255),
    target_media_identity character varying(255),
    media_confirmed_at timestamp with time zone,
    confirmed_participant_sid character varying(255),
    media_cleanup_until timestamp with time zone,
    media_cleanup_complete boolean DEFAULT false NOT NULL,
    CONSTRAINT call_transfer_confirmed CHECK ((((kind)::text <> 'CALL'::text) OR ((status)::text <> 'ACCEPTED'::text) OR ((media_confirmed_at IS NOT NULL) AND (confirmed_participant_sid IS NOT NULL)))),
    CONSTRAINT call_transfer_connection CHECK ((((kind)::text <> 'CALL'::text) OR (live_work AND (queue_code IS NOT NULL) AND (from_media_identity IS NOT NULL) AND (target_media_identity IS NOT NULL)))),
    CONSTRAINT work_transfer_distinct_identity CHECK ((((from_issuer)::text <> (to_issuer)::text) OR ((from_subject)::text <> (to_subject)::text))),
    CONSTRAINT work_transfer_interval CHECK ((expires_at > requested_at)),
    CONSTRAINT work_transfer_kind CHECK (((kind)::text = ANY (ARRAY[('WORK'::character varying)::text, ('CALL'::character varying)::text]))),
    CONSTRAINT work_transfer_status CHECK (((status)::text = ANY (ARRAY[('OFFERED'::character varying)::text, ('CONNECTING'::character varying)::text, ('ACCEPTED'::character varying)::text, ('REJECTED'::character varying)::text, ('CANCELLED'::character varying)::text, ('EXPIRED'::character varying)::text, ('FAILED'::character varying)::text, ('REVOKED'::character varying)::text])))
);


--
-- Name: chat_messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages ALTER COLUMN id SET DEFAULT nextval('public.chat_messages_id_seq'::regclass);


--
-- Name: consultation_revisions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultation_revisions ALTER COLUMN id SET DEFAULT nextval('public.consultation_revisions_id_seq'::regclass);


--
-- Name: internal_messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_messages ALTER COLUMN id SET DEFAULT nextval('public.internal_messages_id_seq'::regclass);


--
-- Name: knowledge_revisions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_revisions ALTER COLUMN id SET DEFAULT nextval('public.knowledge_revisions_id_seq'::regclass);


--
-- Name: agent_presence agent_presence_issuer_subject_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_presence
    ADD CONSTRAINT agent_presence_issuer_subject_key UNIQUE (issuer, subject);


--
-- Name: agent_presence agent_presence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_presence
    ADD CONSTRAINT agent_presence_pkey PRIMARY KEY (id);


--
-- Name: assignment_attempts assignment_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignment_attempts
    ADD CONSTRAINT assignment_attempts_pkey PRIMARY KEY (id);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);


--
-- Name: audit_events audit_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);


--
-- Name: call_recordings call_recordings_organization_id_queue_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_recordings
    ADD CONSTRAINT call_recordings_organization_id_queue_code_key UNIQUE (organization_id, queue_code);


--
-- Name: call_recordings call_recordings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.call_recordings
    ADD CONSTRAINT call_recordings_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_queue_id_sender_key_client_message_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_queue_id_sender_key_client_message_id_key UNIQUE (queue_id, sender_key, client_message_id);


--
-- Name: chat_messages chat_messages_queue_id_sequence_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_queue_id_sequence_key UNIQUE (queue_id, sequence);


--
-- Name: consultation_catalogs consultation_catalogs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultation_catalogs
    ADD CONSTRAINT consultation_catalogs_pkey PRIMARY KEY (owner_id);


--
-- Name: consultation_revisions consultation_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultation_revisions
    ADD CONSTRAINT consultation_revisions_pkey PRIMARY KEY (id);


--
-- Name: consultations consultations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultations
    ADD CONSTRAINT consultations_pkey PRIMARY KEY (id);


--
-- Name: customer_history_links customer_history_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_history_links
    ADD CONSTRAINT customer_history_links_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: follow_up_actions follow_up_actions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follow_up_actions
    ADD CONSTRAINT follow_up_actions_pkey PRIMARY KEY (id);


--
-- Name: follow_up_actions follow_up_actions_request_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follow_up_actions
    ADD CONSTRAINT follow_up_actions_request_key_key UNIQUE (request_key);


--
-- Name: follow_up_events follow_up_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follow_up_events
    ADD CONSTRAINT follow_up_events_pkey PRIMARY KEY (id);


--
-- Name: internal_messages internal_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_messages
    ADD CONSTRAINT internal_messages_pkey PRIMARY KEY (id);


--
-- Name: internal_messages internal_messages_room_id_sender_issuer_sender_subject_clie_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_messages
    ADD CONSTRAINT internal_messages_room_id_sender_issuer_sender_subject_clie_key UNIQUE (room_id, sender_issuer, sender_subject, client_message_id);


--
-- Name: internal_messages internal_messages_room_id_sequence_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_messages
    ADD CONSTRAINT internal_messages_room_id_sequence_key UNIQUE (room_id, sequence);


--
-- Name: internal_room_members internal_room_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_room_members
    ADD CONSTRAINT internal_room_members_pkey PRIMARY KEY (id);


--
-- Name: internal_room_members internal_room_members_room_id_membership_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_room_members
    ADD CONSTRAINT internal_room_members_room_id_membership_id_key UNIQUE (room_id, membership_id);


--
-- Name: internal_rooms internal_rooms_organization_id_creation_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_rooms
    ADD CONSTRAINT internal_rooms_organization_id_creation_key_key UNIQUE (organization_id, creation_key);


--
-- Name: internal_rooms internal_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_rooms
    ADD CONSTRAINT internal_rooms_pkey PRIMARY KEY (id);


--
-- Name: knowledge_documents knowledge_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_documents
    ADD CONSTRAINT knowledge_documents_pkey PRIMARY KEY (id);


--
-- Name: knowledge_revisions knowledge_revisions_document_id_revision_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_revisions
    ADD CONSTRAINT knowledge_revisions_document_id_revision_key UNIQUE (document_id, revision);


--
-- Name: knowledge_revisions knowledge_revisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_revisions
    ADD CONSTRAINT knowledge_revisions_pkey PRIMARY KEY (id);


--
-- Name: membership_roles membership_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_roles
    ADD CONSTRAINT membership_roles_pkey PRIMARY KEY (membership_id, role_id);


--
-- Name: memberships memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_pkey PRIMARY KEY (id);


--
-- Name: organization_invitations organization_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_invitations
    ADD CONSTRAINT organization_invitations_pkey PRIMARY KEY (id);


--
-- Name: organization_invitations organization_invitations_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_invitations
    ADD CONSTRAINT organization_invitations_token_hash_key UNIQUE (token_hash);


--
-- Name: organization_roles organization_roles_organization_id_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_roles
    ADD CONSTRAINT organization_roles_organization_id_name_key UNIQUE (organization_id, name);


--
-- Name: organization_roles organization_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_roles
    ADD CONSTRAINT organization_roles_pkey PRIMARY KEY (id);


--
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);


--
-- Name: queue_items queue_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.queue_items
    ADD CONSTRAINT queue_items_pkey PRIMARY KEY (id);


--
-- Name: role_grants role_grants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_grants
    ADD CONSTRAINT role_grants_pkey PRIMARY KEY (role_id, permission);


--
-- Name: routing_lock routing_lock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.routing_lock
    ADD CONSTRAINT routing_lock_pkey PRIMARY KEY (id);


--
-- Name: support_settings support_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.support_settings
    ADD CONSTRAINT support_settings_pkey PRIMARY KEY (owner_id);


--
-- Name: teams teams_organization_id_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_organization_id_id_key UNIQUE (organization_id, id);


--
-- Name: teams teams_organization_id_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_organization_id_name_key UNIQUE (organization_id, name);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: text_templates text_templates_organization_id_origin_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.text_templates
    ADD CONSTRAINT text_templates_organization_id_origin_id_key UNIQUE (organization_id, origin_id);


--
-- Name: text_templates text_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.text_templates
    ADD CONSTRAINT text_templates_pkey PRIMARY KEY (id);


--
-- Name: timeline_items timeline_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timeline_items
    ADD CONSTRAINT timeline_items_pkey PRIMARY KEY (id);


--
-- Name: queue_items uk1omicrbbofu3lotag0q0ecs6o; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.queue_items
    ADD CONSTRAINT uk1omicrbbofu3lotag0q0ecs6o UNIQUE (request_key);


--
-- Name: memberships uk3t6vxdj7m0m1jjqyfb6av29o7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT uk3t6vxdj7m0m1jjqyfb6av29o7 UNIQUE (organization_id, issuer, subject);


--
-- Name: teams uk7v78offde88bvqjd32ch5vwuk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT uk7v78offde88bvqjd32ch5vwuk UNIQUE (organization_id, name);


--
-- Name: queue_items uk9ccjf9u3cvjig35aali0juyra; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.queue_items
    ADD CONSTRAINT uk9ccjf9u3cvjig35aali0juyra UNIQUE (code);


--
-- Name: consultations ukafr39fvxcbf3cjt1wahpwd4ap; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consultations
    ADD CONSTRAINT ukafr39fvxcbf3cjt1wahpwd4ap UNIQUE (organization_id, queue_code);


--
-- Name: attachments ukbbxtbv647h0bptsvaq66pesqe; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT ukbbxtbv647h0bptsvaq66pesqe UNIQUE (file_id);


--
-- Name: agent_presence ukd9tf68p8qnbmlcb6ydmy73at5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_presence
    ADD CONSTRAINT ukd9tf68p8qnbmlcb6ydmy73at5 UNIQUE (issuer, subject);


--
-- Name: text_templates ukex6y6ga36bqd4oo5tx9mfegfg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.text_templates
    ADD CONSTRAINT ukex6y6ga36bqd4oo5tx9mfegfg UNIQUE (organization_id, origin_id);


--
-- Name: organization_roles ukhih29eqh686g6a7o9nwodu0p1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_roles
    ADD CONSTRAINT ukhih29eqh686g6a7o9nwodu0p1 UNIQUE (organization_id, name);


--
-- Name: attachments ukivtfwpgvliuhj86flavrs7op5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT ukivtfwpgvliuhj86flavrs7op5 UNIQUE (organization_id, queue_code, request_id);


--
-- Name: customers ukmkwx1x9mthieapj92cpxq5msc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukmkwx1x9mthieapj92cpxq5msc UNIQUE (code);


--
-- Name: organizations uktk0wi6yv24buriu6ige0s6ox5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT uktk0wi6yv24buriu6ige0s6ox5 UNIQUE (public_code);


--
-- Name: work_files work_files_organization_id_owner_kind_owner_id_uploader_iss_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_files
    ADD CONSTRAINT work_files_organization_id_owner_kind_owner_id_uploader_iss_key UNIQUE (organization_id, owner_kind, owner_id, uploader_issuer, uploader_subject, request_id);


--
-- Name: work_files work_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_files
    ADD CONSTRAINT work_files_pkey PRIMARY KEY (id);


--
-- Name: work_transfer_events work_transfer_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_transfer_events
    ADD CONSTRAINT work_transfer_events_pkey PRIMARY KEY (id);


--
-- Name: work_transfers work_transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_transfers
    ADD CONSTRAINT work_transfers_pkey PRIMARY KEY (id);


--
-- Name: work_transfers work_transfers_request_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_transfers
    ADD CONSTRAINT work_transfers_request_key_key UNIQUE (request_key);


--
-- Name: agent_presence_organization; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agent_presence_organization ON public.agent_presence USING btree (organization_id);


--
-- Name: assignment_history; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX assignment_history ON public.assignment_attempts USING btree (organization_id, queue_code, offered_at DESC);


--
-- Name: assignment_one_active_agent; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX assignment_one_active_agent ON public.assignment_attempts USING btree (presence_id) WHERE ((outcome)::text = ANY (ARRAY[('OFFERED'::character varying)::text, ('RINGING'::character varying)::text]));


--
-- Name: assignment_one_active_queue; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX assignment_one_active_queue ON public.assignment_attempts USING btree (organization_id, queue_code) WHERE ((outcome)::text = ANY (ARRAY[('OFFERED'::character varying)::text, ('RINGING'::character varying)::text]));


--
-- Name: attachments_owner_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attachments_owner_scope ON public.attachments USING btree (organization_id, owner_issuer, owner_subject);


--
-- Name: attachments_team_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX attachments_team_scope ON public.attachments USING btree (organization_id, team_id);


--
-- Name: call_recordings_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX call_recordings_pending ON public.call_recordings USING btree (state, retry_at);


--
-- Name: call_transfer_cleanup_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX call_transfer_cleanup_pending ON public.work_transfers USING btree (id) WHERE (((kind)::text = 'CALL'::text) AND (media_cleanup_until IS NOT NULL) AND (NOT media_cleanup_complete));


--
-- Name: consultation_report_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX consultation_report_period ON public.consultations USING btree (organization_id, created_at);


--
-- Name: consultation_revisions_owner_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX consultation_revisions_owner_scope ON public.consultation_revisions USING btree (organization_id, owner_issuer, owner_subject);


--
-- Name: consultation_revisions_record; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX consultation_revisions_record ON public.consultation_revisions USING btree (organization_id, consultation_id);


--
-- Name: consultation_revisions_team_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX consultation_revisions_team_scope ON public.consultation_revisions USING btree (organization_id, team_id);


--
-- Name: consultations_owner_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX consultations_owner_scope ON public.consultations USING btree (organization_id, owner_issuer, owner_subject);


--
-- Name: consultations_request_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX consultations_request_key ON public.consultations USING btree (request_key);


--
-- Name: consultations_team_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX consultations_team_scope ON public.consultations USING btree (organization_id, team_id);


--
-- Name: customer_history_links_customer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_history_links_customer ON public.customer_history_links USING btree (organization_id, customer_code, linked_at DESC);


--
-- Name: customers_owner_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customers_owner_scope ON public.customers USING btree (organization_id, owner_issuer, owner_subject);


--
-- Name: customers_team_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customers_team_scope ON public.customers USING btree (organization_id, team_id);


--
-- Name: follow_up_actions_owner_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX follow_up_actions_owner_scope ON public.follow_up_actions USING btree (organization_id, owner_issuer, owner_subject);


--
-- Name: follow_up_actions_team_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX follow_up_actions_team_scope ON public.follow_up_actions USING btree (organization_id, team_id);


--
-- Name: follow_up_event_history; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX follow_up_event_history ON public.follow_up_events USING btree (organization_id, follow_up_id, id DESC);


--
-- Name: follow_up_identity_schedule; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX follow_up_identity_schedule ON public.follow_up_actions USING btree (owner_issuer, owner_subject, status, scheduled_at);


--
-- Name: follow_up_one_active_identity; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX follow_up_one_active_identity ON public.follow_up_actions USING btree (owner_issuer, owner_subject) WHERE ((status)::text = 'IN_PROGRESS'::text);


--
-- Name: follow_up_schedule_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX follow_up_schedule_scope ON public.follow_up_actions USING btree (organization_id, status, scheduled_at);


--
-- Name: followup_report_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX followup_report_period ON public.follow_up_actions USING btree (organization_id, action_type, created_at);


--
-- Name: idx6w6b6rb93r0fsds4w1m3ubd86; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx6w6b6rb93r0fsds4w1m3ubd86 ON public.audit_events USING btree (organization_id, occurred_at);


--
-- Name: idx_audit_org_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_org_time ON public.audit_events USING btree (organization_id, occurred_at);


--
-- Name: internal_members_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX internal_members_active ON public.internal_room_members USING btree (membership_id, active, room_id);


--
-- Name: knowledge_org_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX knowledge_org_updated ON public.knowledge_documents USING btree (organization_id, updated_at DESC, id);


--
-- Name: queue_callback_once; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX queue_callback_once ON public.queue_items USING btree (callback_follow_up_id) WHERE (callback_follow_up_id IS NOT NULL);


--
-- Name: queue_items_owner_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX queue_items_owner_scope ON public.queue_items USING btree (organization_id, owner_issuer, owner_subject);


--
-- Name: queue_items_team_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX queue_items_team_scope ON public.queue_items USING btree (organization_id, team_id);


--
-- Name: queue_report_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX queue_report_period ON public.queue_items USING btree (organization_id, created_at);


--
-- Name: queue_support_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX queue_support_expiry ON public.queue_items USING btree (support_expires_at) WHERE ((support_expires_at IS NOT NULL) AND ((status)::text = ANY (ARRAY[('WAITING'::character varying)::text, ('PROCESSING'::character varying)::text])));


--
-- Name: queue_unlinked_phone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX queue_unlinked_phone ON public.queue_items USING btree (organization_id, phone_key, created_at DESC) WHERE ((customer_code IS NULL) AND ((status)::text = 'COMPLETED'::text));


--
-- Name: text_templates_owner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX text_templates_owner ON public.text_templates USING btree (organization_id, scope, owner_issuer, owner_subject);


--
-- Name: timeline_items_owner_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX timeline_items_owner_scope ON public.timeline_items USING btree (organization_id, owner_issuer, owner_subject);


--
-- Name: timeline_items_team_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX timeline_items_team_scope ON public.timeline_items USING btree (organization_id, team_id);


--
-- Name: work_transfer_history; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX work_transfer_history ON public.work_transfer_events USING btree (organization_id, transfer_id, id);


--
-- Name: work_transfer_inbox; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX work_transfer_inbox ON public.work_transfers USING btree (organization_id, to_issuer, to_subject, status, requested_at DESC);


--
-- Name: work_transfer_one_active_record; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX work_transfer_one_active_record ON public.work_transfers USING btree (organization_id, consultation_id) WHERE ((status)::text = ANY (ARRAY[('OFFERED'::character varying)::text, ('CONNECTING'::character varying)::text]));


--
-- Name: work_transfer_one_live_target; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX work_transfer_one_live_target ON public.work_transfers USING btree (to_issuer, to_subject) WHERE (((status)::text = ANY (ARRAY[('OFFERED'::character varying)::text, ('CONNECTING'::character varying)::text])) AND live_work);


--
-- Name: assignment_attempts assignment_attempts_presence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assignment_attempts
    ADD CONSTRAINT assignment_attempts_presence_id_fkey FOREIGN KEY (presence_id) REFERENCES public.agent_presence(id);


--
-- Name: chat_messages chat_messages_queue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES public.queue_items(id) ON DELETE CASCADE;


--
-- Name: membership_permissions fk9w43kho3m5q79jufqso0rrcf2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_permissions
    ADD CONSTRAINT fk9w43kho3m5q79jufqso0rrcf2 FOREIGN KEY (membership_id) REFERENCES public.memberships(id);


--
-- Name: follow_up_events follow_up_events_follow_up_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.follow_up_events
    ADD CONSTRAINT follow_up_events_follow_up_id_fkey FOREIGN KEY (follow_up_id) REFERENCES public.follow_up_actions(id) ON DELETE CASCADE;


--
-- Name: internal_messages internal_messages_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_messages
    ADD CONSTRAINT internal_messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.internal_rooms(id);


--
-- Name: internal_room_members internal_room_members_membership_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_room_members
    ADD CONSTRAINT internal_room_members_membership_id_fkey FOREIGN KEY (membership_id) REFERENCES public.memberships(id);


--
-- Name: internal_room_members internal_room_members_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_room_members
    ADD CONSTRAINT internal_room_members_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.internal_rooms(id);


--
-- Name: internal_rooms internal_rooms_creator_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_rooms
    ADD CONSTRAINT internal_rooms_creator_member_id_fkey FOREIGN KEY (creator_member_id) REFERENCES public.memberships(id);


--
-- Name: internal_rooms internal_rooms_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.internal_rooms
    ADD CONSTRAINT internal_rooms_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: invitation_permissions invitation_permissions_invitation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitation_permissions
    ADD CONSTRAINT invitation_permissions_invitation_id_fkey FOREIGN KEY (invitation_id) REFERENCES public.organization_invitations(id);


--
-- Name: knowledge_documents knowledge_documents_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_documents
    ADD CONSTRAINT knowledge_documents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: knowledge_revisions knowledge_revisions_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_revisions
    ADD CONSTRAINT knowledge_revisions_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.knowledge_documents(id);


--
-- Name: membership_roles membership_roles_membership_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_roles
    ADD CONSTRAINT membership_roles_membership_id_fkey FOREIGN KEY (membership_id) REFERENCES public.memberships(id);


--
-- Name: membership_roles membership_roles_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_roles
    ADD CONSTRAINT membership_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.organization_roles(id);


--
-- Name: memberships membership_team_org; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT membership_team_org FOREIGN KEY (organization_id, team_id) REFERENCES public.teams(organization_id, id);


--
-- Name: organization_roles organization_roles_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_roles
    ADD CONSTRAINT organization_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: role_grants role_grants_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_grants
    ADD CONSTRAINT role_grants_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.organization_roles(id);


--
-- Name: teams teams_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: teams teams_organization_id_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_organization_id_parent_id_fkey FOREIGN KEY (organization_id, parent_id) REFERENCES public.teams(organization_id, id);


--
-- Name: text_templates text_templates_origin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.text_templates
    ADD CONSTRAINT text_templates_origin_id_fkey FOREIGN KEY (origin_id) REFERENCES public.text_templates(id);


--
-- Name: work_files work_files_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_files
    ADD CONSTRAINT work_files_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: work_transfer_events work_transfer_events_transfer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_transfer_events
    ADD CONSTRAINT work_transfer_events_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES public.work_transfers(id);


--
-- Name: work_transfers work_transfers_consultation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_transfers
    ADD CONSTRAINT work_transfers_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id);


--
-- Name: work_transfers work_transfers_from_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_transfers
    ADD CONSTRAINT work_transfers_from_member_id_fkey FOREIGN KEY (from_member_id) REFERENCES public.memberships(id);


--
-- Name: work_transfers work_transfers_to_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_transfers
    ADD CONSTRAINT work_transfers_to_member_id_fkey FOREIGN KEY (to_member_id) REFERENCES public.memberships(id);


--
-- PostgreSQL database dump complete
--

-- Required single-row coordinator created by V10 in existing environments.
INSERT INTO public.routing_lock(id) VALUES (1);
