-- Preserve legacy requests verbatim; free-form dates/names are never treated as confirmed schedules.
ALTER TABLE follow_up_actions
 ADD COLUMN version bigint NOT NULL DEFAULT 0,
 ADD COLUMN proposed_at timestamptz,
 ADD COLUMN scheduled_at timestamptz,
 ADD COLUMN scheduled_end_at timestamptz,
 ADD COLUMN time_zone varchar(100),
 ADD COLUMN duration_minutes integer,
 ADD COLUMN assigned_member_id bigint,
 ADD COLUMN assigned_name varchar(255),
 ADD COLUMN creator_issuer varchar(255),
 ADD COLUMN creator_subject varchar(255),
 ADD COLUMN creator_name varchar(255),
 ADD COLUMN updated_at timestamptz,
 ADD COLUMN started_at timestamptz,
 ADD COLUMN finished_at timestamptz,
 ADD COLUMN outcome text,
 ADD COLUMN request_key varchar(64) UNIQUE,
 ADD COLUMN request_fingerprint varchar(64);
CREATE INDEX follow_up_schedule_scope ON follow_up_actions(organization_id,status,scheduled_at);
CREATE INDEX follow_up_identity_schedule ON follow_up_actions(owner_issuer,owner_subject,status,scheduled_at);
CREATE UNIQUE INDEX follow_up_one_active_identity ON follow_up_actions(owner_issuer,owner_subject) WHERE status='IN_PROGRESS';
ALTER TABLE follow_up_actions ADD CONSTRAINT follow_up_confirmed_interval CHECK
 (status NOT IN ('SCHEDULED','IN_PROGRESS') OR (scheduled_at IS NOT NULL AND scheduled_end_at IS NOT NULL AND scheduled_end_at>scheduled_at
 AND duration_minutes IS NOT NULL AND duration_minutes BETWEEN 5 AND 480 AND time_zone IS NOT NULL AND assigned_member_id IS NOT NULL
 AND owner_issuer IS NOT NULL AND owner_subject IS NOT NULL));
CREATE TABLE follow_up_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 organization_id varchar(64) NOT NULL,
 follow_up_id bigint NOT NULL REFERENCES follow_up_actions(id) ON DELETE CASCADE,
 action varchar(32) NOT NULL, actor_issuer varchar(255) NOT NULL, actor_subject varchar(255) NOT NULL,
 actor_name varchar(255) NOT NULL, occurred_at timestamptz NOT NULL, reason varchar(2000) NOT NULL,
 before_snapshot text, after_snapshot text NOT NULL
);
CREATE INDEX follow_up_event_history ON follow_up_events(organization_id,follow_up_id,id DESC);

-- Reading keeps each writer's existing data scope. Assignment is a separate permission;
-- only an existing organization administrator receives it automatically.
INSERT INTO membership_permissions(membership_id,permissions)
 SELECT DISTINCT membership_id,'followup:read' FROM membership_permissions WHERE permissions='followup:write';
INSERT INTO membership_permissions(membership_id,permissions)
 SELECT DISTINCT p.membership_id,'followup:assign' FROM membership_permissions p JOIN memberships m ON m.id=p.membership_id
 WHERE p.permissions='organization:admin' AND m.data_scope='ORGANIZATION';
UPDATE memberships SET version=version+1 WHERE id IN
 (SELECT membership_id FROM membership_permissions WHERE permissions='followup:read');
INSERT INTO role_grants(role_id,permission,data_scope)
 SELECT role_id,'followup:read',data_scope FROM role_grants WHERE permission='followup:write';
INSERT INTO role_grants(role_id,permission,data_scope)
 SELECT role_id,'followup:assign',data_scope FROM role_grants WHERE permission='organization:admin' AND data_scope='ORGANIZATION';
UPDATE organization_roles SET version=version+1 WHERE id IN
 (SELECT role_id FROM role_grants WHERE permission IN ('followup:read','followup:assign'));
