CREATE TABLE work_transfers (
 id varchar(36) PRIMARY KEY, organization_id varchar(64) NOT NULL,
 consultation_id bigint NOT NULL REFERENCES consultations(id), queue_code varchar(64),
 version bigint NOT NULL DEFAULT 0, record_version bigint NOT NULL,
 from_member_id bigint NOT NULL REFERENCES memberships(id), from_issuer varchar(255) NOT NULL, from_subject varchar(255) NOT NULL,
 from_name varchar(255) NOT NULL, to_member_id bigint NOT NULL REFERENCES memberships(id), to_issuer varchar(255) NOT NULL,
 to_subject varchar(255) NOT NULL, to_name varchar(255) NOT NULL, to_team_id varchar(64),
 requester_issuer varchar(255) NOT NULL, requester_subject varchar(255) NOT NULL, requester_name varchar(255) NOT NULL,
 owner_issuer varchar(255), owner_subject varchar(255), team_id varchar(64),
 status varchar(32) NOT NULL, reason varchar(2000) NOT NULL, memo text NOT NULL,
 requested_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, finished_at timestamptz,
 outcome varchar(2000), request_key varchar(64) NOT NULL UNIQUE, request_fingerprint varchar(64) NOT NULL,
 CONSTRAINT work_transfer_interval CHECK(expires_at>requested_at),
 CONSTRAINT work_transfer_distinct_identity CHECK(from_issuer<>to_issuer OR from_subject<>to_subject),
 CONSTRAINT work_transfer_status CHECK(status IN ('OFFERED','ACCEPTED','REJECTED','CANCELLED','EXPIRED','FAILED','REVOKED'))
);
CREATE UNIQUE INDEX work_transfer_one_active_record ON work_transfers(organization_id,consultation_id) WHERE status='OFFERED';
CREATE INDEX work_transfer_inbox ON work_transfers(organization_id,to_issuer,to_subject,status,requested_at DESC);
CREATE TABLE work_transfer_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 organization_id varchar(64) NOT NULL, transfer_id varchar(36) NOT NULL REFERENCES work_transfers(id),
 action varchar(32) NOT NULL, actor_issuer varchar(255) NOT NULL, actor_subject varchar(255) NOT NULL,
 actor_name varchar(255) NOT NULL, occurred_at timestamptz NOT NULL, reason varchar(2000) NOT NULL
);
CREATE INDEX work_transfer_history ON work_transfer_events(organization_id,transfer_id,id);

-- Keep existing grant scopes. No read/write grant is created without the corresponding record authority.
INSERT INTO membership_permissions(membership_id,permissions)
 SELECT membership_id,'consultation:transfer' FROM membership_permissions WHERE permissions='consultation:write';
INSERT INTO membership_permissions(membership_id,permissions)
 SELECT membership_id,'transfer:read' FROM membership_permissions WHERE permissions='consultation:read';
UPDATE memberships SET version=version+1 WHERE id IN
 (SELECT membership_id FROM membership_permissions WHERE permissions='consultation:transfer' OR permissions='transfer:read');
INSERT INTO role_grants(role_id,permission,data_scope)
 SELECT role_id,'consultation:transfer',data_scope FROM role_grants WHERE permission='consultation:write';
INSERT INTO role_grants(role_id,permission,data_scope)
 SELECT role_id,'transfer:read',data_scope FROM role_grants WHERE permission='consultation:read';
UPDATE organization_roles SET version=version+1 WHERE id IN
 (SELECT role_id FROM role_grants WHERE permission='consultation:transfer' OR permission='transfer:read');
