CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id VARCHAR(255), actor_issuer VARCHAR(255) NOT NULL,
  actor_subject VARCHAR(255) NOT NULL, action VARCHAR(255) NOT NULL,
  target VARCHAR(255), details VARCHAR(6000), occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_org_time ON audit_events(organization_id, occurred_at);
CREATE TABLE IF NOT EXISTS support_settings (
  owner_id VARCHAR(255) PRIMARY KEY, version BIGINT NOT NULL DEFAULT 0,
  title VARCHAR(150), description VARCHAR(500), button_label VARCHAR(100),
  primary_color VARCHAR(7), logo_url VARCHAR(1000)
);
CREATE TABLE IF NOT EXISTS organization_invitations (
  id VARCHAR(255) PRIMARY KEY, organization_id VARCHAR(255) NOT NULL,
  issuer VARCHAR(255) NOT NULL, recipient_email VARCHAR(255) NOT NULL,
  token_hash VARCHAR(255) NOT NULL UNIQUE, expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  cancelled BOOLEAN NOT NULL DEFAULT FALSE, accepted_subject VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS invitation_permissions (
  invitation_id VARCHAR(255) NOT NULL REFERENCES organization_invitations(id),
  permission VARCHAR(255)
);
